# Site settings
title: "Резюме Ларин А.А."
description: "Резюме Ларин Алексей Александрович"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ларин Алексей Александрович"
resume_title:                   "Java разработчик (Junior"
resume_contact_email:           "79300324898@yandex.ru"
resume_contact_telephone:       "8-930-032-4898"
resume_contact_address:         ""
resume_header_contact_info: "Владимир | 8-930-032-4898 | 79300324898@yandex.ru"
resume_header_intro: "<p>Возраст 26 лет</p>
<p></p>
<p>Телефон: 8-930-032-4898</p>
<p>e-mail: 79300324898@yandex.ru</p>
<p>Skype: roof-less</p>
<p></p>
<p>Трудоустроен, но в поисках работы. Общий стаж по 1С более 3 лет.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_experience:      true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/mrroofless"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/mr.roofless"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  resume_instagram_url:         "https://www.instagram.com/mr.roofless/"
  resume_website_url:           "https://vk.com/mr_roofless"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
